CREATE TABLE KNW_TAGS (
  TAG_ID INT NOT NULL AUTO_INCREMENT,
  TAG_NOME VARCHAR(45) NOT NULL,
  PRIMARY KEY (TAG_ID));

CREATE TABLE KNW_USUARIOS (
  USU_NOME VARCHAR(45) NOT NULL,
  USU_EMAIL VARCHAR(45) NOT NULL,
  USU_SENHA VARCHAR(60) NOT NULL,
  PRIMARY KEY (USU_NOME));

CREATE TABLE KNW_DENUNCIA (
  DEN_ID INT NOT NULL AUTO_INCREMENT,
  DEN_DESCRICAO VARCHAR(250) NOT NULL,
  DEN_USU_NOME VARCHAR(45) NOT NULL,
  PRIMARY KEY (DEN_ID),
  CONSTRAINT DEN_USU_NOME
   FOREIGN KEY (DEN_USU_NOME)
   REFERENCES KNW_USUARIOS (USU_NOME));

CREATE TABLE knw_pergunta (
  PER_ID INT AUTO_INCREMENT,
  PER_TITULO VARCHAR(255) NOT NULL,
  PER_DESCRICAO TEXT,
  PER_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PER_USU_NOME VARCHAR(45) NOT NULL,
  PER_DEN_ID INT NULL,
  PRIMARY KEY (PER_ID),
  CONSTRAINT PER_USU_NOME
    FOREIGN KEY (PER_USU_NOME)
    REFERENCES KNW_USUARIOS (USU_NOME),
  CONSTRAINT PER_DEN_ID
    FOREIGN KEY (PER_DEN_ID)
    REFERENCES KNW_DENUNCIA (DEN_ID));

CREATE TABLE KNW_FEEDBACK (
  FDB_ID INT NOT NULL AUTO_INCREMENT,
  FDB_DESCRICAO VARCHAR(250) NOT NULL,
  FDB_USU_NOME VARCHAR(45) NOT NULL,
  PRIMARY KEY (FDB_ID),
  CONSTRAINT FDB_USU_NOME
    FOREIGN KEY (FDB_USU_NOME)
    REFERENCES KNW_USUARIOS (USU_NOME));

CREATE TABLE KNW_RESPOSTA (
  RES_ID INT NOT NULL AUTO_INCREMENT,
  RES_DESCRICAO VARCHAR(250) NOT NULL,
  RES_PER_ID INT NOT NULL,
  RES_USU_NOME VARCHAR(45) NOT NULL,
  RES_FDB_ID INT NULL,
  RES_DEN_ID INT NULL,
  PRIMARY KEY (RES_ID),
  CONSTRAINT RES_FDB_ID
    FOREIGN KEY (RES_FDB_ID)
    REFERENCES KNW_FEEDBACK (FDB_ID),
  CONSTRAINT RES_PER_ID
    FOREIGN KEY (RES_PER_ID)
    REFERENCES KNW_PERGUNTA (PER_ID),
  CONSTRAINT RES_DEN_ID
    FOREIGN KEY (RES_DEN_ID)
    REFERENCES KNW_DENUNCIA (DEN_ID),
  CONSTRAINT RES_USU_NOME
    FOREIGN KEY (RES_USU_NOME)
    REFERENCES KNW_USUARIOS (USU_NOME));

CREATE TABLE PERGUNTA_TAGS (
  PER_ID INT NOT NULL,
  TAG_ID INT NOT NULL,
  PRIMARY KEY (PER_ID, TAG_ID),
  CONSTRAINT PER_ID
    FOREIGN KEY (PER_ID)
    REFERENCES KNW_PERGUNTA (PER_ID),
  CONSTRAINT TAG_ID
    FOREIGN KEY (TAG_ID)
    REFERENCES KNW_TAGS (TAG_ID));
